# Generated by Django 5.1.2 on 2024-11-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0002_rename_title_jobopening_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementsession',
            name='students_selected',
        ),
        migrations.RemoveField(
            model_name='placementsession',
            name='time',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='seassion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='placeapp.placementsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementsession',
            name='Mode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementsession',
            name='session_end',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementsession',
            name='session_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementsession',
            name='student_selected',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementsession',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
    ]
