# Generated by Django 5.1.2 on 2024-11-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0003_remove_placementsession_students_selected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementsession',
            old_name='Mode',
            new_name='mode',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='seassion',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='placeapp.placementsession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementsession',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placeapp.companyrecruiter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter')], default='student', max_length=10),
        ),
    ]
