# Generated by Django 5.1.2 on 2024-11-15 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0004_rename_mode_placementsession_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecruiter',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placeapp.company'),
        ),
    ]
