# Generated by Django 5.1.2 on 2024-11-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0006_alter_placementsession_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='skills',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
