# Generated by Django 5.1.2 on 2024-11-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0008_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='anything_else',
            field=models.TextField(blank=True, help_text='Add any additional information.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='certification',
            field=models.TextField(blank=True, help_text='List certifications (if any).', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education_level',
            field=models.CharField(choices=[('Graduation', 'Graduation'), ('Master', 'Master')], default=1, help_text='Select your education level.', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default=1, help_text='Enter a valid email address.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter your expected salary.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(blank=True, help_text='Describe your work experience (if any).', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='field_of_study',
            field=models.CharField(default=1, help_text='Select your field of study.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(default=1, help_text='Enter your current location.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default=1, help_text='Enter your full name.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default=1, help_text='Enter your phone number.', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(default=1, help_text='List your skills separated by commas.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of application submission.'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default=1, help_text='Write a detailed cover letter.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=1, help_text='Upload your resume.', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
