# Generated by Django 5.1.2 on 2024-11-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0011_jobapplication_contacted_jobapplication_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placeapp.jobopening'),
            preserve_default=False,
        ),
    ]
